### ISSUE TITLE
Trouble running it

### ISSUE THREAD

**Issue by OSINT007** [eth0izzle/the-endorser#8]
I've installed Phantomjs as I can't seem to install chromedrive
when I run `python the-endorser.py linkedinuser1 linkedinuser2` I get the following error:
`Traceback (most recent call last):
  File "the-endorser.py", line 3, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse`

If I run `python3 the-endorser.py linkedinuser1 linkedinuser2` then I get the following error:
`Traceback (most recent call last):
  File "the-endorser.py", line 38, in <module>
    with LinkedInClient(config.email, config.password, webdriver=driver.get(driver_path), save_cookie=config.save_cookie) as client:
  File "/root/the-endorser/drivers/chromedriver.py", line 15, in get
    return webdriver.Chrome(executable_path=driver_path, chrome_options=chrome_options)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 151, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 240, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)`

I don't know what's going on. I'm not very experienced with linux.

I'm running Kali Linux
Verified that I have phantomjs version 2.1.1

any help would be amazing!

Thank you!

**Comment by eth0izzle** [comment]
I

**Comment by eth0izzle** [comment]
Is Chrome (not chromedriver) installed to `/opt/google/chrome/chrome`?
